# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Jules
tagline:          'Our 😋 Blog'
description:      'On ne change pas une équipe qui gagne.'
url:              https://accueil.bolte.cc
baseurl:          /

author:
  name:           'Benjamin Bolte and Chi Le'
  url:            https://accueil.bolte.cc

paginate:         5

github:
  repo:           https://github.com/codekansas/accueil

plugins:          [jekyll-paginate, jekyll-gist]
